version: "3.7"
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"

  prometheus1:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prom1/prometheus.yml:/etc/prometheus/prometheus.yml"
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--web.enable-lifecycle"]

  prometheus2:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - "./prom2/prometheus.yml:/etc/prometheus/prometheus.yml"
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--web.enable-lifecycle"]

  prometheus3:
    image: prom/prometheus
    ports:
      - "9092:9090"
    volumes:
      - "./prom3/prometheus.yml:/etc/prometheus/prometheus.yml"
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--web.enable-lifecycle"]


  accumulator:
    image: prom/prometheus
    ports:
      - "9099:9090"
    volumes:
      - "./accumulator/prometheus.yml:/etc/prometheus/prometheus.yml"
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--web.enable-lifecycle"]


  avalanche1:
    image: quay.io/freshtracks.io/avalanche
    ports:
      - "9001:9001"

  avalanche2:
    image: quay.io/freshtracks.io/avalanche
    ports:
      - "9002:9001"

  avalanche3:
    image: quay.io/freshtracks.io/avalanche
    ports:
      - "9003:9001"
